# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-09 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chatuser_ip'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chatuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userban',
            managers=[
            ],
        ),
    ]
