# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161023_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='phone',
        ),
        migrations.AlterUniqueTogether(
            name='chatuser',
            unique_together=set([('username', 'channel')]),
        ),
    ]
