# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-23 04:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0006_auto_20161023_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('url', models.URLField(help_text='Site that chat will use', max_length=255, unique=True, verbose_name='URL')),
                ('domain', models.CharField(help_text='Domain of URL', max_length=255, unique=True, verbose_name='Domain')),
                ('email', models.EmailField(blank=True, help_text='Email for validation owner of this domain', max_length=254, null=True, verbose_name='Email')),
                ('is_approved', models.BooleanField(default=False, help_text='This channel is approved', verbose_name='Is approved')),
                ('channel', models.ForeignKey(help_text='Channel for this site', on_delete=django.db.models.deletion.CASCADE, related_name='site_channel', to='channels.Channel')),
                ('owner', models.ForeignKey(help_text='Owner of the domain', on_delete=django.db.models.deletion.CASCADE, related_name='domain_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
