# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-23 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Channel for this site', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_channel', to='channels.Channel'),
        ),
    ]
