# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20161024_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheWHOIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain', max_length=255, verbose_name='Domain')),
                ('name', models.CharField(blank=True, help_text='Name of registrant', max_length=255, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, help_text='Phone of registrant', max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(help_text='Email of registrant', max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'cached domain',
                'verbose_name_plural': 'Cached WHOIS domains',
            },
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'website', 'verbose_name_plural': 'Websites'},
        ),
    ]
