# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20161027_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='approve_code',
            field=models.CharField(auto_created=uuid.uuid4, blank=True, help_text='Code for sending to email', max_length=20, null=True, verbose_name='Approve code'),
        ),
        migrations.AddField(
            model_name='website',
            name='email_page',
            field=models.URLField(blank=True, help_text='Page with email for approving', null=True, verbose_name='Email page'),
        ),
    ]
