# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_auto_20161029_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='approve_code',
        ),
        migrations.RemoveField(
            model_name='website',
            name='email',
        ),
        migrations.RemoveField(
            model_name='website',
            name='email_page',
        ),
        migrations.RemoveField(
            model_name='website',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.CharField(help_text='Domain of URL', max_length=255, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(help_text='Site that chat will use', max_length=255, verbose_name='URL'),
        ),
    ]
