# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_auto_20161103_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='website',
            unique_together=set([('domain', 'owner')]),
        ),
    ]
