# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-09 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_auto_20161007_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',), 'verbose_name': 'message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
