# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
