# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-09 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20161004_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='site',
            field=models.URLField(help_text='Site that chat will use', unique=True, verbose_name='URL'),
        ),
    ]
