# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-23 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20161022_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='sites',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
